server:
  port: 9000
spring:
  application:
    name: service-gateway
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8841
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: websocket_routes
          predicates:
            - Path=/websocketserver/**
          uri: lb://websocketserver
          filters:
            - StripPrefix=1

# 单节点OK
#      routes:
#        - id: websocket
#          predicates:
#            - Path=/websocket_server/**
#          uri: http://localhost:8071
#          filters:
#            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    root: debug